using TradingPlatformHackathon.DTOs;

namespace TradingPlatformHackathon.MediatR.GetAllNotInWorkPurchaseRequests;

public record GetAllNotInWorkPurchaseRequestsResponse(List<GetPurchaseRequestDto> PurchaseRequests);