using TradingPlatformHackathon.DTOs;

namespace TradingPlatformHackathon.MediatR.GetPurchaseRequestsInWorkByBuyerId;

public record GetPurchaseRequestsInWorkByBuyerIdResponse(List<GetPurchaseRequestsInWorkByBuyerIdDto> PurchaseRequestsInWork);