using TradingPlatformHackathon.DTOs;

namespace TradingPlatformHackathon.MediatR.GetPurchaseResponsesNotInWorkByBuyerId;

public record GetPurchaseResponsesNotInWorkByBuyerIdResponse(List<GetPurchaseResponsesByBuyerIdDto> PurchaseResponses);