using TradingPlatformHackathon.DTOs;

namespace TradingPlatformHackathon.MediatR.GetPurchaseResponsesInWorkBySupplierId;

public record GetPurchaseResponsesInWorkBySupplierIdResponse(List<GetPurchaseResponsesInWorkBySupplierIdDto> PurchaseResponsesInWork);