using TradingPlatformHackathon.DTOs;

namespace TradingPlatformHackathon.MediatR.GetPurchaseResponsesByBuyerId;

public record GetPurchaseResponsesByBuyerIdResponse(List<GetPurchaseResponsesByBuyerIdDto> PurchaseResponses);